name: cc13_polygottal
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cloud_firestore: ^0.13.0+1
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:

flutter:
  uses-material-design: true

  assets:
    - images/dart_logo.png
